define({
    "root": {
        "status"    : "Status",
        "admin"     : "Administration",

        "lblHome"   : "Home",
        "lblWelcome": "Welcome",
        "lblRefresh": "Refresh",
        "lblContact": "Contact",
        "lblHelp"   : "Help",
        "lblLogout": "Logout",
        "lblAdmin": "Admin",
        "lblAgency": "Agency",
        "lblDepartment": "Department",
        "lblMedicalCondition": "Medical Condition",
        "lblMedicalConditionTier": "Medical Condition Tier",
        "lblShelterType": "Shelter Type",
        "lblSheltereeStaffRatio": "Shelteree Staff Ratio",
        "lblStaffSpecialty": "Staff Specialty",
        "lblStaffType": "Staff Type",
        "lblTransportationType": "Transportation Type",
        "lblDisposition": "Disposition",
        "lblEquipmentSupply": "Equipment Supply",
        "lblShelterIdentification": "Shelter Identification",
        "lblQuestion": "Question",
        "lblShelterStatus": "Shelter Status",
        "lblEvent": "Event",
        "lblStaff": "Staff",
        "lblAttendance": "Attendance",
        "lblShortList": "Short List",
        "lblExtendedList": "Extended List",
        "lblDownloadTemplate": "Download Template",
        "lblUploadData": "Upload Data",
        "lblDownloadData": "Download Data",
        "lblShelteree": "Shelteree",
        "lblSheltereeList": "Shelteree List",
        "lblSheltereeDischargeList": "Shelteree Discharge List",
        "lblSheltereeMedicalUpdateList": "Shelteree Medical Update List",
        "lblReports": "Reports",
        "lblRefresh": "Refresh",
        "lblStaffAttendance": "Staff Attendance"
    }
});
